GET http://localhost:3003/api/blogs/

###
POST http://localhost:3003/api/blogs/ HTTP/1.1
content-type: application/json

{
    "title": "sample title",
    "author": "John Doe",
    "url": "http://www.xyz.com",
    "likes": 2456
}

###
PUT http://localhost:3003/api/blogs/63fc6741bf1ad5a041077471 HTTP/1.1
content-type: application/json

{
    "title": "Awesome epic title",
    "author": "John Doe",
    "url": "http://www.xyz.com",
    "likes": 24567855
}

###
DELETE http://localhost:3003/api/blogs/63fc38f31237c7975e5260b7